### PR TITLE
[CLOUD-2702] weird usage label in image info

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.jboss.org/browse/CLOUD-2702
Signed-off-by: Ken Wills <kwills@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by bstansberry** [comment]
@luck3y If you get feedback from Bilge, let me know. This is marketing talk, and TBH if we're doing marketing talk then marketers should write it. If it's engineering talk instead I think the "vague" thing there now is fine, as it's true -- you use our image as a base for creating your own.

**Comment by luck3y** [comment]
@bstansberry OK, understood.

**Review by rcernich — DISMISSED** [review]

**Comment by luck3y** [comment]
@bstansberry has QE approved, so we can merge if you approve.

**Review by bstansberry — APPROVED** [review]

**Comment by luck3y** [comment]
This has changed in the base layers, so closing for now.

**Pull request closed without merging**
