### PR TITLE
update for sprint 15

### PR DESCRIPTION
**Pull request by luck3y**
Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by luck3y** [comment]
@bstansberry Can you approve this? I'm not sure if your approval is enough to let me merge this or not.

**Comment by bstansberry** [comment]
@luck3y AIUI this is the equivalent of a component upgrade PR in WildFly/EAP. It's updating the image to use a later version of cct_module.

If this were a component upgrade PR in WF/EAP I'd want to know why the component was being upgraded and I'd ask for a JIRA. So I guess I do here as well.

**Comment by bstansberry** [comment]
Also, I don't have write access (which tbh i don't mind) and it says "At least 1 approving review is required by reviewers with write access."

**Comment by luck3y** [comment]
@bstansberry Thats fine, I'll see what we have for an analog for a component upgrade jira. What happens is that at the end of a sprint, the cct_modules tag gets moved to the name of that sprint, and released images (GA branch, -CP branch) are updated to use that tag.

WRT approvals, we should think about that. @rcernich given our discussion about you doing reviews in product repos this morning, what do you think? We should just be reviewing / approving these changes ourselves right?

**Comment by bstansberry** [comment]
I don't mean to impose a bunch of process requirements if this is something that's standard practice.

**Comment by rcernich** [comment]
Correct.  Note, however that we talked about using an overrides.yaml to make merges easier between the branches, e.g.
```yaml
schema_version: 1

modules:
  repositories:
  - name: cct_module
    git:
      url: https://github.com/jboss-openshift
      ref: sprint-15
```

Checking that file into the repo, then building with `concreate --overrides=release-overrides.yaml ... build`.  This would be used for the ga and cp branches, while dev would keep up with master.

@goldmann, is this what you had in mind?

**Comment by rcernich** [comment]
...and I didn't answer your question.  Yes, as long as the changes aren't tied to changes going into cct_modules, merge at will.

**Comment by rcernich** [comment]
(even with changes to cct_module, you can still merge, you just might end up out of sync)

**Comment by luck3y** [comment]
@rcernich Great thanks, I'll do that. 

I'm just left with the mechanical problem of it's just me submitting these PRs then, and they're blocked until I get a review, and I really ought not to review my own work ;)

@bstansberry Are you up to doing more reviews? Should we look for someone else?

**Comment by rcernich** [comment]
@luck3y I'm happy to review.  Just add me to the list and I'll take a look.  We should probably have other committers on the repo so you have somebody to review it.  You can always abuse your administrator privileges. ;)

**Review by rcernich — APPROVED** [review]
LGTM.  Consider using overrides.yaml to ease merges in the future.

**Comment by bstansberry** [comment]
@luck3y I'm fine doing reviews; I consider that to be part of my key responsibilities. I'm likely to be a bit cautious at first (i.e. like here) which will probably be both a good and a bad thing. :)

**Comment by luck3y** [comment]
@bstansberry OK, I don't seem to be able to give you write access, but @rcernich can, then you can be a bit more effective for reviews :)

**Pull request merged**
